### ISSUE TITLE
KMS server discovery

### ISSUE THREAD

**Issue by xXcodgerXx** [Py-KMS-Organization/py-kms#45] opened 2021-12-13 04:39 UTC
I added a DNS record for py-kms in pihole using the method shown here. [Linkie](https://discourse.pi-hole.net/t/add-srv-kms-record/20775)

A fresh install of Win 10 Pro on the client machine using the VL key provided by MS it is not activated automatically. 
Running `nslookup -type=srv _vlmcs._tcp`  from the client machine shows the py-kms server.
I enter the key again manually using `slmgr /ipk VLKEY` just to make sure it is correct. 
Running `slmgr /ato` gives the following error (see attached screencaps)
If I specify the kms server using `slmgr /skms mykms.server` then run ` slmgr /ato` it activates successfully. 

Am I doing something wrong?

Thank you for your time. 

BTW I am using the latest py-kms

![2021-12-12 23_34_24-Test - VMware Workstation](https://user-images.githubusercontent.com/26036808/145753365-5573da1f-d344-4bcb-a75d-b1f179363ec8.png)
![2021-12-12 23_35_20-Test - VMware Workstation](https://user-images.githubusercontent.com/26036808/145753369-82d4a3fc-2aab-4c9a-afa2-1e175374db81.png)
![2021-12-12 23_35_46-Test - VMware Workstation](https://user-images.githubusercontent.com/26036808/145753370-623f1dc2-fcc8-47c7-a9c1-5c4577e84fd3.png)
![2021-12-12 23_36_13-Test - VMware Workstation](https://user-images.githubusercontent.com/26036808/145753371-994b4233-0d13-4ffe-8471-1124947689e0.png)

**Comment by simonmicro** [comment] 2021-12-23 15:51
Hi,
as first: I have never used Microsofts DNS SRV records. There is a good chance that they only work e.g. in AD scenarios...
Could you try to modify the SRV record as follows and then retest?

- Add the IPv4 instead of the hostname (of the py-kms server)
- Add the FQDN (maybe you are e.g. using a Fritz!Box, which automatically sets the domain name of the network to `fritz.box`)

As a final step (to determine if the problem is on py-kms or your network), try to use Wireshark and see if Windows is really sending out packets to the py-kms host and if the py-kms host is even receiving it (and replying).

Please post your results (and _anonymize_ them!) for further investigation.

Thanks!

**Comment by Matthew-Beckett** [comment] 2021-12-23 16:36
I believe what might be happening here is that you've created a record in your DNS server with the correct prefix, however you've provided no domain suffix. In the NSLOOKUP which returns successfully you do not provide a suffix and nor do you on the /skms example.

I suspect that your DHCP server is providing a DNS suffix Windows is appending and subsequently the vlmcs lookup is never hitting the record you created in PiHole.

Can you enable detailed request logging in PiHole and provide DNS server logs of the vlmcs request make by /ato?

**Comment by xXcodgerXx** [comment] 2021-12-23 17:42
> Hi, as first: I have never used Microsofts DNS SRV records. There is a good chance that they only work e.g. in AD scenarios... Could you try to modify the SRV record as follows and then retest?
> 
> * Add the IPv4 instead of the hostname (of the py-kms server)
> * Add the FQDN (maybe you are e.g. using a Fritz!Box, which automatically sets the domain name of the network to `fritz.box`)
> 
> As a final step (to determine if the problem is on py-kms or your network), try to use Wireshark and see if Windows is really sending out packets to the py-kms host and if the py-kms host is even receiving it (and replying).
> 
> Please post your results (and _anonymize_ them!) for further investigation.
> 
> Thanks!

I changed the hostname to the IPv4 address, no change in the results. I also tried wireshark and didn't seen any traffic going to the IPv4 address of the kms server regardless of using the IPv4 address or hostname in the KMS DNS entry. 

I also added a bogus DNS suffix to the client and the error message was different when trying to auto-activate. It indicated the KMS server could not be found.

Just for the heck of it, I did `slmgr /skms mykms.server` then `slmgr /ato` and it activated successfully but I still did not see any traffic going to the IPv4 address of the KMS server. Maybe it is encrypted or something? 

The client is running inside a VMWare Workstation VM with a bridged network connection. Perhaps this makes a difference.

**Comment by Matthew-Beckett** [comment] 2021-12-29 14:56
> I still did not see any traffic going to the IPv4 address of the KMS server. Maybe it is encrypted or something?

I believe you should still see something, can you filter in Wireshark by `tcp port 1688`?

**Comment by Oratorian** [comment] 2022-01-01 01:51
If you have a DNS Server add a new SRV record to your DNS

_vlmcs			SRV	0 1 1688 domain.tld.


after that you can add this domain with /skms-domain domain.tld and slmgr will do the lookup.

**Comment by Oratorian** [comment] 2022-01-01 01:55
btw its not /skms it is skms-domain for autorecovery in almgr

**Comment by xXcodgerXx** [comment] 2022-01-01 05:30
@Matthew-Beckett @simonmicro 

I restored the VM prior to specifying the kms server with `slmgr /skms` then ran `slmgr /ato` nothing was sent anywhere with a destination port of 1688.  I then added `slmgr /skms mykms.server` then  `slmgr /ato` and I saw the packets sent to the KMS server in wireshark and it activated. 

So it is NOT sending packets or requests to the KMS server until it is specified on the client with `slmgr /skms mykms.server`

I'm starting to agree - using the DNS entry for KMS auto-discovery probably requires being part of a Windows domain.





@Oratorian 

I am trying to get it to activate out of the box without having to run any 'slmgr' command. I used `slmgr /skms mykms.server` to specify the KMS server to confirm it would activate.

**Comment by Oratorian** [comment] 2022-01-01 16:13
No the skms-domain works regardlessly of being part of an AD, i got it working and use it on all my systems.

If you want to check set skms-domain to amhosting.de and do /ato

**Comment by simonmicro** [comment] 2022-01-06 17:02
Soooo.... Should we close this or do we need to add something to the documentation?

**Comment by Matthew-Beckett** [comment] 2022-01-09 23:15
> Soooo.... Should we close this or do we need to add something to the documentation?

Either way, this issue is deployment-dependent and related to Windows discovery of KMS servers and certainly out of the scope of this project to assist.

**Closed by Matthew-Beckett** 2022-01-09 23:15 UTC
Labels: help wanted
