### ISSUE TITLE
Py-KMS on Python Version 3.10 not working

### ISSUE THREAD

**Issue by lodiabloc** [Py-KMS-Organization/py-kms#36] opened 2021-11-21 23:05 UTC
Hello

I want to use py-kms for my homelab test but cannot start the service

here step by step what i have done
- Setup fresh winserver2019 std edition Evaluation (with desktop experience environment)
- Installed latest python (3.10.0) on C:\Program Files\Python310\ (for all users and with PATH Environment)
- installed with pip the dependencies mentioned at https://py-kms.readthedocs.io/en/latest/Getting%20Started.html#dependencies
```
py pip install tzlocal pysqlite3
```
- Unzipped py-kms-master.zip at C:\KMS\
- checking if python works correctly : OK
```
c:\KMS\py-kms>py
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
```
- try to start pykms_Server.py and get an error
```
c:\KMS\py-kms>py pykms_Server.py
Traceback (most recent call last):
  File "c:\KMS\py-kms\pykms_Server.py", line 27, in <module>
    from Etrigan import Etrigan, Etrigan_parser, Etrigan_check, Etrigan_job
  File "c:\KMS\py-kms\Etrigan.py", line 12, in <module>
    from collections import Sequence
ImportError: cannot import name 'Sequence' from 'collections' (C:\Program Files\Python310\lib\collections\__init__.py)

c:\KMS\py-kms>
```

I would like to get some help to know if i missed one step 

thanks you in advance

**Comment by Matthew-Beckett** [comment] 2021-11-22 00:53
Hi @lodiabloc 

In Python 3.3 it seems `Sequence` was moved from `collections` to `collections.abc` which explains this behaviour you're seeing in 3.10.

Alternatively you can use our Docker container to work around the issue.

I will mark this as a confirmed bug and we'll set to work fixing this.

Thanks,
Matt

**Comment by AraHaan** [comment] 2021-11-22 00:59
Another issue as well is that it also will try to use the SO_REUSEPORT which does not exist on windows.

**Comment by simonmicro** [comment] 2021-12-05 17:16
This is not a bug per-se as we clearly state that we are using Python 3.6.9+ in our readme and as https://endoflife.date/python reports the versions before that breaking change are far beyond their end-of-life dates.

I would prefer to close this - what do your think @Matthew-Beckett ?

**Comment by Matthew-Beckett** [comment] 2021-12-09 16:22
> This is not a bug per-se as we clearly state that we are using Python 3.6.9+ in our readme and as https://endoflife.date/python reports the versions before that breaking change are far beyond their end-of-life dates.
> 
> I would prefer to close this - what do your think @Matthew-Beckett ?

@simonmicro I'm a little confused as to your comment. You state that we use 3.6.9 however if so `Sequence` would have been moved from `collections` to `collections.abc` and thus this would be an actual bug as our import reference is for a version that is EoL no?

3.6.9 is going EoL in two weeks anyway, I think we should upgrade to 3.9 or 3.10, squash this bug and complete the chore of upgrading whilst we're there.

**Comment by simonmicro** [comment] 2021-12-09 16:34
Nvm - I can confirm it.

**Comment by simonmicro** [comment] 2021-12-09 16:34
On it.

**Comment by simonmicro** [comment] 2021-12-09 17:02
Should work now?!

**Closed by simonmicro** 2021-12-09 17:02 UTC
Labels: invalid

**Comment by simonmicro** [comment] 2021-12-09 17:07
You are right. I'll create PRs from now on... The `next` branch will be used from now on for direct commits :)

**Comment by lodiabloc** [comment] 2021-12-09 21:05
Thanks for the fix its now work fine

**Comment by CRCinAU** [comment] 2021-12-23 11:31
This is a much better fix - as it supports both:

```
try:
    from collections.abc import Sequence
except ImportError:
    from collections import Sequence
```
