### ISSUE TITLE
Docker says time is mismatched

### ISSUE THREAD

**Issue by dudefoxlive** [Py-KMS-Organization/py-kms#63] opened 2022-04-07 23:24 UTC
Recently setup Py-KMS in docker and noticed this when looking at logs. I have another py-kms LXC in proxmox and have no such warnings. I can provide more info if needed. I checked date and time and both are correct though maybe a minuet or so apart. 

Thu, 07 Apr 2022 18:56:20 WARNING  Okay, something went horribly wrong while localizing the request time (proceeding anyways): Timezone offset does not match system offset: 0 != -14400. Please, check your config files.
Thu, 07 Apr 2022 18:56:20 WARNING  With count = 26, activated client could be detected as not genuine !

**Comment by SoLoR1** [comment] 2022-04-10 17:09
Try to set timezone of the docker container with TZ enviroment variable... add somewhere when creating docker -e TZ="Europe/Berlin" (or whatever your timezone is). If docker is run on linux you can also mount /etc/localtime to py-kms /etc/localtime with -v /etc/localtime:/etc/localtime:ro (dont forget ro, it makes it read only).

**Comment by simonmicro** [comment] 2022-04-13 11:05
@dudefoxlive Did it work? If yes, please close this issue...

**Comment by dudefoxlive** [comment] 2022-04-13 18:16
> Try to set timezone of the docker container with TZ enviroment variable... add somewhere when creating docker -e TZ="Europe/Berlin" (or whatever your timezone is). If docker is run on linux you can also mount /etc/localtime to py-kms /etc/localtime and set timezone that way with -v /etc/localtime:/etc/localtime:ro (dont forget ro, it makes it read only).

I did this originally when creating it and no. same issue.

**Comment by SoLoR1** [comment] 2022-04-14 06:36
Well its definatly some kind of time inconsistencys.... if its not timezones are you using NTP to set time on server/clients? If you dont, you should... also one other thing... its just a warning anyway :)

**Comment by simonmicro** [comment] 2022-04-15 19:20
-> Caused by: https://github.com/regebro/tzlocal/issues/79

**Comment by simonmicro** [comment] 2022-04-15 19:23
I've triggered a rebuild of the Docker images... Maybe that helps? Otherwise I have to dive deeper what's going on here...

**Comment by dudefoxlive** [comment] 2022-04-15 19:28
I have noticed that the Docker VM is about 10 or so seconds ahead
![image](https://user-images.githubusercontent.com/50186495/163623853-93f58a65-faeb-4890-bfb3-bab6cb302dc9.png)

**Comment by simonmicro** [comment] 2022-04-15 19:38
Huh? This smells like a classic problem, where you do not use the same NTP servers / the docker host has no `ntpd` active... Is this even related?

**Comment by dudefoxlive** [comment] 2022-04-16 17:53
ok so update. I eventually found out that my Domain Controller was about 10 seconds behind and my docker was actually correct. I have fixed the time issue and now my DC is syncing with an NTP server. Same servers as my Docker VM. still after fixing that issue I am still getting the same message as before.

**Comment by edgd1er** [comment] 2022-04-20 16:45
if no tz is defined in the container, utc is set. do you have a diff of -2h with utc ?

**Comment by dudefoxlive** [comment] 2022-04-20 16:54
OK so new update. Setting the ENV TZ=US/Eastern has fixed the issue of saying the localization time being wrong. Now the only warning I am getting is "Wed, 20 Apr 2022 12:52:01 WARNING  With count = 26, activated client could be detected as not genuine !" Any ideas on that?

**Comment by simonmicro** [comment] 2022-04-21 09:52
Glad to hear, that you "fixed" the problem. I sadly have no idea why your timezones were such a mess (maybe even the time of the Docker host is not localized?)...

Regarding the second warning... Try to change the activation count (see params) - but it should be fine...

**Closed by simonmicro** 2022-04-21 09:52 UTC
